sudo: required
services:
  - docker
before_install:
  - docker build -t pankaj/frontend -f Dockerfile.dev .

script:
  - docker run pankaj/frontend npm run test -- --coverage

# deploy:
#   - provider: gae
#   - keyfile: service-account.json
#   - project: frontend

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-app"
  env:  "DockerApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-564267139341"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


